function Indices = Derive_StructuralComplexityVisual(Indices) 
% Structural complexity (visual assessment) was calculated by % Darling et al. (2017), as a linear function of three variables 
beta_0 = 0; % constant coefficient 
beta_1 = 0.5; % total cover 
beta_2 = 0.6; % habitat, crest 
beta_3 = 1.1; % habitat, slope 
beta_4 = -0.3; % branching coral percentage 
Indices.StructuralComplexityVisual = beta_0 + ... 
    beta_1.*Indices.PercentCoralCover + ... 
    beta_2.*Indices.PercentCrest + ... 
    beta_3.*Indices.PercentSlope + ... 
    beta_4.*Indices.PercentBranchingAcroporid; 
end