name: Build Documentation
on:
  push:
    branches:
      - main-doctest
    paths:
      - docs/**
      - .github/workflows/build-docs.yaml

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'main-doctest'

      - run: echo "Building documentation from ${{ github.ref }} on ${{ github.repository }}"

      - name: Download mdBook and build pages
        run: |
          cd docs
          wget https://github.com/rust-lang/mdBook/releases/download/v0.4.14/mdbook-v0.4.14-x86_64-unknown-linux-gnu.tar.gz -O mdbook.tar.gz
          tar -xf mdbook.tar.gz mdbook
          echo $(ls)

          echo "DOCBUILDERROR=0" >> $GITHUB_ENV
          if mdbook build | grep -q 'ERROR'; then
            echo "Error occurred running mdbook"
            echo "DOCBUILDERROR=1" >> $GITHUB_ENV
          fi
          echo "${{ env.DOCBUILDERROR }}"
          rm mdbook
          rm mdbook.tar.gz

      - if: ${{ env.DOCBUILDERROR }} == 0
        name: Commit doc changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -- docs/book
          git commit -m "Documentation build" -a

      - if: ${{ env.DOCBUILDERROR }} == 0
        name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main-doctest
